### PR TITLE
Use a local version of jQuery for offline compat

### PR DESCRIPTION
**Pull request by nicjansma**
If there is no external internet access available, Matador cannot be used because it was pointing to https://ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js.  I found this out on an airplane :)

Since many of the other `js/` files are cached locally, let's just keep a copy of jQuery 2.1.0 as well.

### CODE REVIEW

**Comment by nicjansma** [comment]
Any concerns here?

**Comment by nicjansma** [comment]
@ShaneK If you're still interested in this project, it would be great to get some feedback on this.  Thanks!

**Comment by ShaneK** [comment]
Honestly have no idea why I didn't start with a local copy to begin with since all the other libraries are local copies. Thanks for the PR!

**Comment by ShaneK** [comment]
This is live in version 1.2.2

**Pull request merged**
