### PR TITLE
New Job page. Creates a job given queueName and JSON payload.

### PR DESCRIPTION
**Pull request by peterholdsworth**

### CODE REVIEW

**Comment by nodesocket** [comment]
:+1: would be cool to have this.

**Comment by adityabansod** [comment]
:+1: tried it locally, would be great to have.

**Comment by ShaneK** [comment]
This is a very nice addition, thank you for the PR. Sorry it took me to long to pull in :disappointed:

**Comment by Tomtom777** [comment]
Hello everyone, 

Please, do you have any example of JSON payload ?

Thanks!

**Comment by peterholdsworth** [comment]
Any valid JSON can be enqueued e.g. {} or {"prop":"value"} or
{"prop1":"value1", "prop2":"value2"}

On 18 April 2016 at 09:35, Tomtom777 <notifications@github.com> wrote:

> Hello everyone,
>
> Please, do you have any example of JSON payload ?
>
> Thanks!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ShaneK/Matador/pull/20#issuecomment-211269365>
>



-- 
Peter Holdsworth
peter.j.holdsworth@gmail.com
07771391757

**Comment by Tomtom777** [comment]
Thank you very much!

**Pull request merged**
