### PR TITLE
update matador paths; allow standalone or mounted

### PR DESCRIPTION
**Pull request by ecorkevin**
- add improvements to how matador was handling paths/relative paths
- still allow standalone version of app (works as described in docs previously)
- can now mount matador inside of another app or require it with config
- updated readme with examples
- update bull to 0.2.4
- update info bubble to show stacktrace if it exists when a job has failed

### CODE REVIEW

**Comment by ShaneK** [comment]
Wow, looks very nice. Thank you!

**Comment by ecorkevin** [comment]
Thanks!  Any plans on publishing to npm?

**Comment by ShaneK** [comment]
I didn't have any before, but I guess I could now. I'll try to put it up this evening.

**Comment by ShaneK** [comment]
It has been published under bull-ui
https://www.npmjs.com/package/bull-ui

**Pull request merged**
